### PR TITLE
chore(hotfix/3.2.2): release 3.2.2

### PR DESCRIPTION
**Pull request by yetti**
:robot: I have created a release *beep* *boop*
---

### Miscellaneous

* release 3.2.2 ([5763840](https://github.com/nla/nla-blacklight/commit/5763840c229da668db0bba5bbef3869471aeacff))

### Continuous Integration

* update hotfix workflow ([14b3a34](https://github.com/nla/nla-blacklight/commit/14b3a3484da743ca86a305c5a77b096e9b024eae))

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Comment by yetti** [comment]
@scott-yeadon I generated the release versioning PR for you since I wasn't sure you knew how to do it. It's different from what's in `main` because I cleaned that up before I finished up last month.

**Comment by scott-yeadon** [comment]
> @scott-yeadon I generated the release versioning PR for you since I wasn't sure you knew how to do it. It's different from what's in `main` because I cleaned that up before I finished up last month.

Awesome, I was just about to ask you about it, cos yes, I have absolutely no idea, thanks. So basically I merge this in and the release is created.

**Comment by yetti** [comment]
> > @scott-yeadon I generated the release versioning PR for you since I wasn't sure you knew how to do it. It's different from what's in `main` because I cleaned that up before I finished up last month.
> 
> Awesome, I was just about to ask you about it, cos yes, I have absolutely no idea, thanks. So basically I merge this in and the release is created.

Yup, just merge and the release tags and release itself should be created in a few mins.

**Comment by scott-yeadon** [comment]
> > > @scott-yeadon I generated the release versioning PR for you since I wasn't sure you knew how to do it. It's different from what's in `main` because I cleaned that up before I finished up last month.
> > 
> > 
> > Awesome, I was just about to ask you about it, cos yes, I have absolutely no idea, thanks. So basically I merge this in and the release is created.
> 
> Yup, just merge and the release tags and release itself should be created in a few mins.

Cheers. So for future reference, can I just change the default-branch and bump* properties in the release-hotfix.yml and push it to Git and that will do all the stuff needed to set the autorelease up for hotfixes

**Comment by yetti** [comment]
> Cheers. So for future reference, can I just change the default-branch and bump* properties in the release-hotfix.yml and push it to Git and that will do all the stuff needed to set the autorelease up for hotfixes

Only for hotfixes until what is currently `main` is released into prod. The workflow has been updated in `main` so that it will trigger on `hotfix` branches without any manual manipulation. If you check, there's only one `release-please.yml` workflow in `main` now.

**Comment by scott-yeadon** [comment]
> > Cheers. So for future reference, can I just change the default-branch and bump* properties in the release-hotfix.yml and push it to Git and that will do all the stuff needed to set the autorelease up for hotfixes
> 
> Only for hotfixes until what is currently `main` is released into prod. The workflow has been updated in `main` so that it will trigger on `hotfix` branches without any manual manipulation. If you check, there's only one `release-please.yml` workflow in `main` now.

Oh yeah, I see. So that's why the hotfix branch would have gone to 3.3.0, the same versioning is being used for both normal and hotfix releases.

**Comment by yetti** [comment]
:robot: Release is at https://github.com/nla/nla-blacklight/releases/tag/3.2.2 :sunflower:

**Pull request merged**
