### PR TITLE
BLAC-184: Resize image on record page

### PR DESCRIPTION
**Pull request by paulhagon**
Feels like a really really really ugly way of doing it - sure there must be a much better way

### CODE REVIEW

**Comment by yetti** [comment]
@paulhagon Yes, there could be a better way. 😄 But it'll require changes to https://github.com/nla/nla-blacklight/blob/main/app/presenters/nla_thumbnail_presenter.rb

I created that class to extend Blacklight's ThumbnailPresenter, so we can add our own methods there if we need to. A clean way to determine if the page where the thumbnail is shown on is by checking the `context` property of the `view_config` as you can see on https://github.com/nla/nla-blacklight/blob/e1a204bf48409f139022f8b7a3f48c5cbba84649/app/presenters/nla_thumbnail_presenter.rb#L16

You can add a method above the `private` line in `nla_thumbnail_presenter.rb` like:
```ruby
def is_catalogue_record_page?
  view_config[:key] == :show
end
```

Then call that method in the ERB:
```ruby
<% if presenter.thumbnail.is_catalogue_record_page? %>
do thumbnail stuff for the catalogue record page...
<% else %>
do thumbnail stuff for the search results page...
<% end %>
```

**Comment by yetti** [comment]
@paulhagon That suggestion is totally untested BTW, 😀  just putting things down off the top of my head. If you're not comfortable making the code changes, I'm happy to checkout your branch and do them for you. Thought I'd let you have a go first if you wanted to try it.

**Comment by paulhagon** [comment]
@yetti Files updated with your recommendation & working nicely.

**Comment by yetti** [comment]
@paulhagon  I did a slight refactor to make it a bit cleaner. Also added a test for the new method in the presenter. I'll merge this into main and deploy. Should be in devel and test in a few mins.

**Review by yetti — APPROVED** [review]

**Pull request merged**
